/**
 * Auto-generated fields that should be excluded from update operations.
 * These fields are managed server-side and should not be included in update payloads.
 */
export const AUTO_GENERATED_FIELDS = new Set([
    "_id",
    "_createdAt",
    "_updatedAt",
    "_seq",
    // Also support the client-facing names
    "id",
    "createdAt",
    "updatedAt",
]);

/**
 * Strips auto-generated fields from data before an update operation.
 * This prevents conflicts with server-managed fields like _createdAt.
 */
export function stripAutoGeneratedFields<T extends Record<string, unknown>>(data: T): T {
    const result: Record<string, unknown> = {};
    for (const [key, value] of Object.entries(data)) {
        if (!AUTO_GENERATED_FIELDS.has(key)) {
            result[key] = value;
        }
    }
    return result as T;
}
